# Generated by Django 3.0.3 on 2020-05-19 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('collection_amount', models.FloatField(default=0)),
                ('collection_list', models.ManyToManyField(related_name='collection_customer_set', to='Customers.Customer')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectedCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_date', models.DateField(auto_now_add=True, db_index=True)),
                ('month', month.models.MonthField(auto_now_add=True)),
                ('collected_amount', models.FloatField()),
                ('street', models.CharField(blank=True, max_length=50)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.Customer')),
            ],
            options={
                'unique_together': {('collected_date', 'customer', 'month')},
            },
        ),
    ]
