# Generated by Django 3.0.3 on 2020-05-19 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Setupboxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('street', models.CharField(blank=True, max_length=50)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('payment_amount', models.FloatField(default=0)),
                ('payment_status', models.CharField(choices=[('paid', 'PAID'), ('unpaid', 'UNPAID')], default='unpaid', max_length=6)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('lco_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('setupbox', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Setupboxes.SetupBox')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=50)),
                ('payment_date', models.DateField(db_index=True)),
                ('payment_month', month.models.MonthField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.Customer')),
            ],
            options={
                'unique_together': {('customer', 'payment_month', 'payment_date')},
            },
        ),
    ]
