# Generated by Django 3.0.3 on 2020-06-17 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_type', models.CharField(choices=[('normal', 'NORMAL'), ('internet', 'INTERNET')], default='normal', max_length=10)),
                ('due_amount', models.FloatField(default=0, null=True)),
                ('due_months', models.CharField(blank=True, max_length=2, null=True)),
                ('payment_status', models.CharField(choices=[('paid', 'PAID'), ('unpaid', 'UNPAID')], default='unpaid', max_length=6)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('stbno', models.CharField(max_length=10)),
                ('base_package', models.CharField(choices=[('180', 'BASEPACK180'), ('230', 'BASEPACK230')], default='180', max_length=3)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('base_price', models.FloatField(default=180)),
                ('additional_price', models.FloatField(default=0)),
                ('gst_price', models.FloatField(default=0)),
                ('payment_amount', models.FloatField(default=0)),
                ('box_status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='active', max_length=10)),
                ('deactive_reason', models.CharField(blank=True, max_length=40, null=True)),
                ('channels', models.ManyToManyField(blank=True, related_query_name='channels_set', to='Customers.Channels')),
                ('lco_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='CustomerReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=50)),
                ('payment_date', models.DateTimeField(db_index=True)),
                ('payment_month', month.models.MonthField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='packages',
            field=models.ManyToManyField(blank=True, related_query_name='packages_set', to='Customers.Packages'),
        ),
        migrations.AddConstraint(
            model_name='customerreport',
            constraint=models.UniqueConstraint(fields=('customer', 'payment_month'), name='um'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('stbno',), name='stb'),
        ),
    ]
