# Generated by Django 3.0.3 on 2020-06-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_auto_20200617_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='channels_count',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
