# Generated by Django 3.0.3 on 2020-06-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_auto_20200620_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
