# Generated by Django 3.0.3 on 2020-06-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0006_auto_20200620_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tamil_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
