# Generated by Django 3.0.3 on 2020-05-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BroadcastBouquet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SetupBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxno', models.CharField(max_length=10)),
                ('base_package', models.CharField(choices=[('180', 'BASEPACK180'), ('230', 'BASEPACK230')], default='180', max_length=3)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('base_price', models.FloatField(default=180)),
                ('additional_price', models.FloatField(default=0)),
                ('gst_price', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('box_status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='active', max_length=10)),
                ('deactive_reason', models.CharField(blank=True, max_length=40, null=True)),
                ('addon_packages', models.ManyToManyField(blank=True, related_name='channels_set', related_query_name='clist_set', to='Setupboxes.Channel')),
                ('bouquets', models.ManyToManyField(blank=True, related_name='bouquets_set', related_query_name='bqpack_set', to='Setupboxes.Bouquet')),
                ('broadcast_bouquets', models.ManyToManyField(blank=True, related_name='bcbouquets_set', related_query_name='bcbqpack_set', to='Setupboxes.BroadcastBouquet')),
            ],
            options={
                'verbose_name_plural': 'SetupBoxes',
            },
        ),
    ]
